---

- name: Get current default zone
  shell: firewall-cmd --get-default-zone
  register: default_zone
  changed_when: False

- name: Set default zone
  shell: firewall-cmd --set-default-zone={{ firewalld.default_zone }}
  when: firewalld.default_zone is defined and default_zone.stdout != firewalld.default_zone
